/**
 * Dist repository fetching: download a dist artifact (native-image tar.gz,
 * jar, war) from a beangle dist repository, preferring a binary delta
 * against a local baseline over the whole artifact.
 *
 * The repository layout is the maven2 one, so the same gav strings used for
 * maven work here; the difference is the optional delta:
 *
 *   <base>/<g>/<a>/<version>/<a>-<version>[-<classifier>].<packaging>
 *   <base>/<g>/<a>/<version>/<a>-<oldVersion>_<version>[-<classifier>].<packaging>.diff
 *
 * Deltas are generated by the beangle build plugin (bsdiff against the
 * previous release) and are optional: when the probe finds none, the whole
 * artifact is downloaded instead.
 */
module jstart.distrepo;

import std.array : split;
import std.conv : to;
import std.file : dirEntries, exists, isDir, readText, remove, rename, SpanMode;
import std.path : baseName, dirName;
import std.string : indexOf, replace, strip;

import std.stdio : stderr, writeln;

import jstart.archive : Artifact, parseGav;
import jstart.bspatch : applyBsdiff, bspatchAvailable;
import jstart.gzip : gzipAvailable, gzipTo, gunzipTo;
import jstart.http : downloadFile, downloadFileSmart, remoteExists;
import jstart.repo : LocalRepo, parseSha1Text, sha1OfFile;

/// Default dist repository: the beangle native-image repository.
enum defaultDistRemote = "https://sas.openurp.net/sas/repo/native";

/// Outcome of a fetch: the local path of the artifact.
struct FetchResult {
  bool ok;
  string path;
  /// 由本地基线与增量补丁重建，而非整包下载
  bool viaDelta;
  /// 本地已存在，未发起下载
  bool reused;
  /// 实际使用的仓库地址
  string remote;
}

/// Build the dist repository list from a comma separated spec.
string[] buildDistRemotes(string spec = "") {
  string[] bases;
  foreach (b; spec.split(",")) {
    auto base = b.strip;
    if (base.length == 0) {
      continue;
    }
    while (base.length > 1 && base[$ - 1] == '/') {
      base = base[0 .. $ - 1];
    }
    bases ~= base;
  }
  if (bases.length == 0) {
    bases ~= defaultDistRemote;
  }
  return bases;
}

/// Url of the artifact in a dist repository.
string distUrl(string base, Artifact a) {
  return base ~ a.layoutPath;
}

/// Url of the artifact's .sha1 companion.
string distSha1Url(string base, Artifact a) {
  return base ~ a.sha1.layoutPath;
}

/// Version directory inside the repository.
string distDir(string base, Artifact a) {
  return base ~ "/" ~ a.groupId.replace(".", "/") ~ "/" ~ a.artifactId ~ "/" ~ a.ver;
}

/**
 * Delta file name: `<a>-<old>_<version>[-<classifier>].<packaging>.diff`.
 *
 * The native (tar.gz) deltas carry the classifier (build plugin naming); the
 * maven side war/jar diffs are named without it (`<a>-<old>_<new>.war.diff`).
 */
string deltaFileName(Artifact a, string oldVersion) {
  auto name = a.artifactId ~ "-" ~ oldVersion ~ "_" ~ a.ver;
  if (a.classifier.length && isCompressedTar(a.packaging)) {
    name ~= "-" ~ a.classifier;
  }
  return name ~ "." ~ a.packaging ~ ".diff";
}

/// Url of the delta from `oldVersion` to the artifact version, if published.
string deltaUrl(string base, Artifact a, string oldVersion) {
  return distDir(base, a) ~ "/" ~ deltaFileName(a, oldVersion);
}

/**
 * Fetch `gav` into the local repository. When a delta from `fromVersion`
 * (or from the newest local baseline when omitted) exists upstream, it is
 * downloaded and applied with bspatch, and the rebuilt artifact is verified
 * against the new version's .sha1; otherwise the whole artifact (and its
 * .sha1) is downloaded.
 *
 * A missing delta is a normal outcome, not an error: the client falls back
 * to the whole artifact silently.
 */
FetchResult fetchDist(string gav, string fromVersion, string remoteSpec,
    string localBase, bool verbose = true, string snapshotBase = "") {
  FetchResult r;
  Artifact a;
  try {
    a = parseGav(gav, gav);
  } catch (Exception e) {
    stderr.writeln(e.msg);
    return r;
  }
  auto local = new LocalRepo(localBase, snapshotBase);
  auto bases = buildDistRemotes(remoteSpec);

  // 1) 本地已有：SNAPSHOT 先查独立快照库，再查本地仓库
  auto existing = findLocalArtifact(local, a, verbose);
  if (existing.length) {
    if (verbose) {
      writeln("Using local " ~ existing);
    }
    r.ok = true;
    r.path = existing;
    r.reused = true;
    return r;
  }

  // 2) 基线版本：--from 优先，否则用本地仓库里最接近的较低版本
  auto baseline = fromVersion.strip;
  if (baseline.length == 0) {
    baseline = inferBaselineVersion(local, a);
  }
  if (baseline.length) {
    auto baselineFile = findBaselineFile(local, a, baseline);
    if (baselineFile.length == 0) {
      if (verbose) {
        writeln("No local " ~ baseline ~ " baseline, skip delta " ~ a.ver);
      }
    } else {
      foreach (base; bases) {
        if (!remoteExists(deltaUrl(base, a, baseline))) {
          continue; // 没有 delta 很正常
        }
        if (verbose) {
          writeln("Delta " ~ baseline ~ " -> " ~ a.ver ~ " found at " ~ base);
        }
        if (fetchViaDelta(local, base, a, baseline, baselineFile, verbose)) {
          r.ok = true;
          r.path = localArtifactPath(local, a);
          r.viaDelta = true;
          r.remote = base;
          return r;
        }
        if (verbose) {
          writeln("Delta not usable, falling back to the whole artifact");
        }
        break;
      }
    }
  }

  // 3) 整包（含 .sha1 校验）
  if (downloadWhole(local, bases, a, verbose)) {
    r.ok = true;
    r.path = localArtifactPath(local, a);
    return r;
  }
  if (a.isSnapshot) {
    auto snap = local.snapshotPathOf(a);
    if (snap.length) {
      r.ok = true;
      r.path = snap;
      r.reused = true;
      return r;
    }
  }
  stderr.writeln("Cannot fetch " ~ gav);
  return r;
}

/**
 * 本地落盘路径：SNAPSHOT 版本进独立的快照库（~/.m2/snapshots），正式版进本地仓库
 * （~/.m2/repository），两者互不混合。
 */
string localArtifactPath(LocalRepo local, Artifact a) {
  return (a.isSnapshot ? local.snapshotBase : local.base) ~ a.layoutPath;
}

/**
 * Local artifact path when it is already usable: for SNAPSHOT versions the
 * newest timestamped file in the snapshot repository, then the literal
 * <version>-SNAPSHOT file there; for releases the file in the local
 * repository. A file failing its .sha1 companion is removed (and
 * re-downloaded later).
 */
string findLocalArtifact(LocalRepo local, Artifact a, bool verbose = true) {
  if (a.isSnapshot) {
    auto snap = local.snapshotPathOf(a);
    if (snap.length) {
      return snap;
    }
  }
  auto file = localArtifactPath(local, a);
  if (!exists(file)) {
    return "";
  }
  if (verifyBeside(file)) {
    return file;
  }
  if (verbose) {
    writeln("Error sha1 for " ~ a.raw ~ ",Remove it.");
  }
  remove(file);
  auto sha1File = file ~ ".sha1";
  if (exists(sha1File)) {
    remove(sha1File);
  }
  return "";
}

/// Local file of the baseline version, in the snapshot or the local repository.
string findBaselineFile(LocalRepo local, Artifact a, string baselineVersion) {
  auto old = a.withVersion(baselineVersion);
  if (old.isSnapshot) {
    auto snap = local.snapshotPathOf(old);
    if (snap.length) {
      return snap;
    }
  }
  auto file = localArtifactPath(local, old);
  if (exists(file)) {
    return file;
  }
  return "";
}

/**
 * Newest local version lower than the requested one, used as the delta
 * baseline when --from is omitted. Released versions live in the local
 * repository, snapshots in the snapshot repository.
 */
string inferBaselineVersion(LocalRepo local, Artifact a) {
  string best;
  foreach (root; [local.base, local.snapshotBase]) {
    auto dir = root ~ "/" ~ a.groupId.replace(".", "/") ~ "/" ~ a.artifactId;
    if (!exists(dir) || !isDir(dir)) {
      continue;
    }
    foreach (e; dirEntries(dir, SpanMode.shallow)) {
      if (!e.isDir) {
        continue;
      }
      auto ver = baseName(e.name);
      if (ver == a.ver || compareVersion(ver, a.ver) >= 0) {
        continue;
      }
      auto old = a.withVersion(ver);
      auto present = exists(localArtifactPath(local, old));
      if (!present && old.isSnapshot) {
        present = local.snapshotPathOf(old).length > 0;
      }
      if (!present) {
        continue;
      }
      if (best.length == 0 || compareVersion(ver, best) > 0) {
        best = ver;
      }
    }
  }
  return best;
}

/**
 * 下载整包及其 .sha1，按远程仓库顺序尝试；SNAPSHOT 落到快照库，正式版落到本地仓库。
 */
private bool downloadWhole(LocalRepo local, string[] bases, Artifact a, bool verbose) {
  auto target = localArtifactPath(local, a);
  auto sha1File = target ~ ".sha1";
  foreach (base; bases) {
    if (!downloadFileSmart(distUrl(base, a), target, verbose, a.fileName)) {
      continue;
    }
    // 远程有 .sha1 才校验；没有时按既有依赖下载语义接受
    if (downloadFile(distSha1Url(base, a), sha1File, false, "")) {
      if (!verifyBeside(target)) {
        if (verbose) {
          writeln("Error sha1 for " ~ a.raw ~ ",Remove it.");
        }
        remove(target);
        remove(sha1File);
        continue;
      }
    }
    return true;
  }
  if (verbose) {
    writeln("Not found(" ~ to!string(bases.length) ~ " mirrors):" ~ a.raw);
  }
  return false;
}

/// 与相邻的 .sha1 文件比对；没有 .sha1 时算通过（与依赖下载同语义）。
private bool verifyBeside(string file) {
  auto sha1File = file ~ ".sha1";
  if (!exists(sha1File)) {
    return true;
  }
  auto expected = parseSha1Text(readText(sha1File));
  return expected.length == 40 && expected == sha1OfFile(file);
}

/// 补丁是对未压缩 tar 生成的打包类型：重建后要按 tar -z 的参数压回去。
bool isCompressedTar(string packaging) {
  return packaging == "tar.gz" || packaging == "tgz";
}

/**
 * Download the delta and the new .sha1, rebuild the artifact with bspatch and
 * verify the result. False means "delta unusable, download the whole thing";
 * the temporary files are removed, the local baseline is left untouched.
 */
private bool fetchViaDelta(LocalRepo local, string base, Artifact a,
    string baselineVersion, string baselineFile, bool verbose) {
  auto packed = isCompressedTar(a.packaging);
  if (!bspatchAvailable() || (packed && !gzipAvailable())) {
    if (verbose) {
      stderr.writeln("bspatch/bzip2/gzip not found, skip delta " ~ a.ver);
    }
    return false;
  }
  auto target = localArtifactPath(local, a);
  auto dir = dirName(target);
  auto patchFile = dir ~ "/" ~ deltaFileName(a, baselineVersion);
  auto patchSha1 = patchFile ~ ".sha1";
  auto sha1File = target ~ ".sha1";
  auto baselineTar = target ~ ".baseline.tar";
  auto rebuiltTar = target ~ ".rebuilt.tar";
  auto rebuilt = target ~ ".delta";
  scope (exit) {
    foreach (f; [baselineTar, rebuiltTar, rebuilt]) {
      if (exists(f)) {
        remove(f);
      }
    }
  }

  auto patchUrl = deltaUrl(base, a, baselineVersion);
  if (!downloadFileSmart(patchUrl, patchFile, verbose, baseName(patchFile))) {
    return false;
  }
  // 补丁自身的 sha1：服务端有就校验，没有就跳过（与依赖下载同语义）
  if (downloadFile(patchUrl ~ ".sha1", patchSha1, false, "")) {
    auto expectedPatch = parseSha1Text(readText(patchSha1));
    if (expectedPatch.length != 40 || expectedPatch != sha1OfFile(patchFile)) {
      if (verbose) {
        stderr.writeln("Error sha1 for " ~ patchFile ~ ",ignore the delta.");
      }
      return false;
    }
  }
  // 目标版本的 sha1 必须拿到，否则无法验证重建结果
  if (!downloadFileSmart(distSha1Url(base, a), sha1File, verbose, a.sha1.fileName)) {
    if (verbose) {
      stderr.writeln("Cannot find " ~ a.ver ~ " .sha1, ignore the delta.");
    }
    return false;
  }
  auto expected = parseSha1Text(readText(sha1File));
  if (expected.length != 40) {
    return false;
  }
  // tar.gz：补丁比对的是解压后的 tar（压缩流之间 diff 几乎没有节省），
  // 所以先 gunzip 本地基线，打完补丁再按 tar -z 的参数压回去；
  // jar/war 等本身就是可比对的文件，直接打补丁。
  if (packed) {
    if (!gunzipTo(baselineFile, baselineTar)) {
      return false;
    }
    if (!applyBsdiff(baselineTar, patchFile, rebuiltTar, verbose)) {
      return false;
    }
    if (!gzipTo(rebuiltTar, rebuilt)) {
      return false;
    }
  } else {
    if (!applyBsdiff(baselineFile, patchFile, rebuilt, verbose)) {
      return false;
    }
  }
  auto actual = sha1OfFile(rebuilt);
  if (actual != expected) {
    if (verbose) {
      stderr.writeln("Rebuilt " ~ a.fileName ~ " does not match its sha1, ignore the delta.");
    }
    return false;
  }
  if (exists(target)) {
    remove(target);
  }
  rename(rebuilt, target);
  if (verbose) {
    writeln("Rebuilt " ~ target ~ " from delta " ~ baselineVersion);
  }
  return true;
}

/// Compare two version strings: dot/dash separated, numeric segments compare numerically.
int compareVersion(string x, string y) {
  auto xs = splitVersion(x);
  auto ys = splitVersion(y);
  auto count = xs.length > ys.length ? xs.length : ys.length;
  foreach (i; 0 .. count) {
    auto a = i < xs.length ? xs[i] : "0";
    auto b = i < ys.length ? ys[i] : "0";
    auto an = isNumeric(a);
    auto bn = isNumeric(b);
    if (an && bn) {
      auto av = to!long(a);
      auto bv = to!long(b);
      if (av != bv) {
        return av < bv ? -1 : 1;
      }
    } else if (a != b) {
      return a < b ? -1 : 1;
    }
  }
  return 0;
}

private string[] splitVersion(string ver) {
  string[] parts;
  string current;
  foreach (c; ver) {
    if (c == '.' || c == '-') {
      parts ~= current;
      current = "";
    } else {
      current ~= c;
    }
  }
  parts ~= current;
  return parts;
}

private bool isNumeric(string s) {
  if (s.length == 0) {
    return false;
  }
  foreach (c; s) {
    if (c < '0' || c > '9') {
      return false;
    }
  }
  return true;
}
